"""LLM execution constants."""

CHAR_TOKEN_RATIO_EN = 3.5
CHAR_TOKEN_RATIO_ZH = 1.5
CHAR_TOKEN_RATIO = CHAR_TOKEN_RATIO_EN

MAX_API_RETRIES = 3
INITIAL_RETRY_DELAY_SECONDS = 1
API_REQUEST_TIMEOUT_SECONDS = 180

MIN_REQUEST_INTERVAL_SECONDS = 0.5
MAX_REQUESTS_PER_MINUTE = 60
RATE_LIMIT_WARNINGS_ENABLED = True

RESPONSE_CACHE_ENABLED = False
RESPONSE_CACHE_MAX_SIZE = 100
RESPONSE_CACHE_TTL_SECONDS = 3600
